### ISSUE TITLE
Bug: Hardcoded `pingone.com` address in multiple files.  Repo will not work for EU, AP, CA regions

### ISSUE THREAD

**Issue by patrickcping** [pingidentity-developers-experience/ping-integration-example-packages#39]
Files containing `pingone.com`:

- /davinci-api-registration-pkg/davinci-api-registration-sample-app/dashboard.html
- /davinci-api-registration-pkg/davinci-api-registration-sample-app/index.html
- /davinci-api-registration-pkg/terraform/davinci.tf
- /davinci-api-risk-pkg/davinci-api-risk-sample-app/dashboard.html
- /davinci-api-risk-pkg/davinci-api-risk-sample-app/index.html
- /davinci-api-risk-pkg/terraform/davinci.tf
- /davinci-registration-pkg/davinci-registration-sample-app/dashboard.html
- /davinci-registration-pkg/davinci-registration-sample-app/index.html
- /davinci-registration-pkg/terraform/davinci.tf
- /davinci-sso-protect-pkg/davinci-sso-protect-sample-app/dashboard.html
- /davinci-sso-protect-pkg/davinci-sso-protect-sample-app/index.html
- /davinci-sso-protect-pkg/terraform/data.tf
- /davinci-sso-protect-pkg/terraform/davinci-sso-protect-flow.json
- /davinci-sso-protect-pkg/terraform/davinci.tf
- /oidc-sdk-pkg/oidc-sdk-sample-app/dashboard.html
- /oidc-sdk-pkg/oidc-sdk-sample-app/index.html
- /oidc-sdk-pkg/terraform/data.tf
- /ping-one-protect-pkg/ping-one-protect-sample-app/public/index.html
- /ping-one-protect-pkg/ping-one-protect-sample-app/server.js
- /ping-one-protect-pkg/terraform/data.tf

**Comment by michaelsanchez-pingidentity** [comment]
@patrickcping this is being resolved today so we can get it into the Thursday release. #186124060. @zhannaavanesova  is working it.

**Comment by zhannaavanesova** [comment]
This issue was resolved with our latest release v1.4.0.
