### ISSUE TITLE
Warning: Attribute Deprecated

### ISSUE THREAD

**Issue by hinespj** [pingidentity-developers-experience/ping-integration-example-packages#63]
with pingone_application_resource_grant.oidc_sdk_sample_app_openid,
│   on resources.tf line 114, in resource "pingone_application_resource_grant" "oidc_sdk_sample_app_openid":
│  114:   scopes = [
│  115:     data.pingone_resource_scope.openid_profile.id,
│  116:     data.pingone_resource_scope.openid_phone.id,
│  117:     data.pingone_resource_scope.openid_email.id
│  118:   ]
│ 
│ This parameter is deprecated and will be made read-only in a future release.  This attribute should be replaced with the `scope_names` parameter
│ instead.

**Comment by hinespj** [comment]
This error occurred in the davinci-oidc_sdk-ciam_passwordless_solution-pkg

**Comment by michaelsanchez-pingidentity** [comment]
There are a few deprecated attributes and resources because of coming changes from the Terraform provider. This message is intentional as a warning. But deprecated is still supported. No need to report warning messages.
