### ISSUE TITLE
 "GET /global.js" Error (404): "Not found". davinci-oidc_sdk-ciam_passwordless_solution-pkg

### ISSUE THREAD

**Issue by hinespj** [pingidentity-developers-experience/ping-integration-example-packages#66]
global.js file not generated by Terraform

**Comment by michaelsanchez-pingidentity** [comment]
@hinespj I honestly think you need to do a hard reset on your project. These are not errors we're experiencing and we're on our final QA today for this sprint. It looks like you have a domino effect of errors happening.

**Comment by michaelsanchez-pingidentity** [comment]
If you haven't run `git add ...` on your changes, I would `git stash` them all and re-test. If that's not feasible, I would re-clone the project elsewhere and start from scratch testing one change at a time. If you need support, go to our team's channel. GH issues is for submitting bugs or feature requests.
